### ISSUE TITLE
As a user I want to be able to create a game room in order to play with other users.

### ISSUE THREAD

**Issue by vichcruz** [sopra-fs24-group-25/SketchyPhone-Server#1]
### Acceptance Criteria
- [x] After creating the game room the user (admin) can copy an invite link or invite code to share with others.
- [x] Upon entering the created game room, the user is shown the list of other users that have joined the game room.
- [x] The list of users shows who is the current admin of the game room.
- [x] Inside the game room the current admin user can leave the game room and the admin role is reassigned.
- [x] As an admin user I want to be able to set basic settings. (number of cycles, time limit per action, text-to-speech enabled/disabled)

### Client Development Tasks
- [x] sopra-fs24-group-25/SketchyPhone-Client#26
- [x] sopra-fs24-group-25/SketchyPhone-Client#27
- [x] sopra-fs24-group-25/SketchyPhone-Client#28
- [x] sopra-fs24-group-25/SketchyPhone-Client#29
- [x] sopra-fs24-group-25/SketchyPhone-Client#30
- [x] sopra-fs24-group-25/SketchyPhone-Client#31
- [x] sopra-fs24-group-25/SketchyPhone-Client#32
- [x] sopra-fs24-group-25/SketchyPhone-Client#33
- [x] sopra-fs24-group-25/SketchyPhone-Client#34
- [x] sopra-fs24-group-25/SketchyPhone-Client#35

### Server Development Tasks
- [x] #64
- [x] #65
- [x] #66
- [x] #67
- [x] #68
- [x] #69
- [x] #70
- [x] #71
