### ISSUE TITLE
As a user inside an active game room I want to be able to customise my user profile.

### ISSUE THREAD

**Issue by vichcruz** [sopra-fs24-group-25/SketchyPhone-Server#2]
### Acceptance Criteria
- [x] As a user I want to be able to change my username.
- [x] As a user I want to be able to draw my user profile avatar.
- [x] A user can only change their user profile and not of other participants.

### Client Development Tasks
- [x] sopra-fs24-group-25/SketchyPhone-Client#36
- [x] sopra-fs24-group-25/SketchyPhone-Client#37
- [x] sopra-fs24-group-25/SketchyPhone-Client#38
- [x] sopra-fs24-group-25/SketchyPhone-Client#39
- [x] sopra-fs24-group-25/SketchyPhone-Client#40
- [x] sopra-fs24-group-25/SketchyPhone-Client#41

### Server Development Tasks
- [x] #78
- [x] #79
- [x] #80
