### ISSUE TITLE
As a user I want to be able to join an active game room.

### ISSUE THREAD

**Issue by vichcruz** [sopra-fs24-group-25/SketchyPhone-Server#3]
### Acceptance Criteria
- [x] A user can join an active game room with an invite link and invite code.
- [x] If a game room is already running a game, the user will be navigated to the waiting room.

### Client Development Tasks
- [x] sopra-fs24-group-25/SketchyPhone-Client#5
- [x] sopra-fs24-group-25/SketchyPhone-Client#6
- [x] sopra-fs24-group-25/SketchyPhone-Client#7
- [x] sopra-fs24-group-25/SketchyPhone-Client#8
- [x] sopra-fs24-group-25/SketchyPhone-Client#10
- [x] sopra-fs24-group-25/SketchyPhone-Client#11

### Server Development Tasks
- [x] #40
- [x] #41
- [x] #42
