### ISSUE TITLE
As a user participating in an active game session, I want to be able to input a text prompt at the start of the game.

### ISSUE THREAD

**Issue by vichcruz** [sopra-fs24-group-25/SketchyPhone-Server#4]
### Acceptance Criteria
- [x] When a game is started, each participating user will be required to input a text prompt.
- [x] A user’s text prompt must not be empty or longer than the character limit, otherwise an error message will be shown to the user.
- [x] A user can click on a button to submit their text prompt.
- [x] If the timer has run out before a user has submitted, the current state of their input will be submitted instead.

### Client Development Tasks
- [x] sopra-fs24-group-25/SketchyPhone-Client#19
- [x] sopra-fs24-group-25/SketchyPhone-Client#20
- [x] sopra-fs24-group-25/SketchyPhone-Client#21
- [x] sopra-fs24-group-25/SketchyPhone-Client#22
- [x] sopra-fs24-group-25/SketchyPhone-Client#23
- [x] sopra-fs24-group-25/SketchyPhone-Client#24
- [x] sopra-fs24-group-25/SketchyPhone-Client#25

### Server Development Tasks
- [x] sopra-fs24-group-25/SketchyPhone-Server#51
- [x] sopra-fs24-group-25/SketchyPhone-Server#52
- [x] sopra-fs24-group-25/SketchyPhone-Server#53
