### ISSUE TITLE
As a user participating in an active game session, I want to be able to draw images on the screen.

### ISSUE THREAD

**Issue by vichcruz** [sopra-fs24-group-25/SketchyPhone-Server#5]
### Acceptance Criteria
- [x] After a user has been shown another user’s text prompt, they must be presented with an empty canvas and drawing tools.
- [x] As a user, I want to be able to choose basic drawing tools and different colours.
- [x] A user can click on a button to submit their drawings.
- [x] If the timer has run out before a user has submitted, the current state of their input will be submitted instead.
- [x] A user should be able to undo drawing actions.

### Client Development Tasks
- [x] sopra-fs24-group-25/SketchyPhone-Client#42
- [x] sopra-fs24-group-25/SketchyPhone-Client#43
- [x] sopra-fs24-group-25/SketchyPhone-Client#44
- [x] sopra-fs24-group-25/SketchyPhone-Client#45
- [x] sopra-fs24-group-25/SketchyPhone-Client#46
- [x] sopra-fs24-group-25/SketchyPhone-Client#47
- [x] sopra-fs24-group-25/SketchyPhone-Client#48
- [x] sopra-fs24-group-25/SketchyPhone-Client#49

### Server Development Tasks
- [x] #89
- [x] #90
- [x] #91
- [x] #92
