### ISSUE TITLE
As a user, I want to be able to see the flow of the text-to-drawing-to-text cycles at the end of the game.

### ISSUE THREAD

**Issue by vichcruz** [sopra-fs24-group-25/SketchyPhone-Server#6]
### Acceptance Criteria
- [x] At the end of the game, each flow, starting from a random user’s initial text prompt to the last text prompt, will be separately shown in chronological order to all participating users.
- [x] The text prompts will be vocalised with a text-to-speech synthesis api.
- [x] The presentation will be supported by various audio effects.
- [x] Each text and drawing is labelled with the creator’s username.

### Client Development Tasks
- [x] sopra-fs24-group-25/SketchyPhone-Client#9
- [x] sopra-fs24-group-25/SketchyPhone-Client#13
- [x] sopra-fs24-group-25/SketchyPhone-Client#12
- [x] sopra-fs24-group-25/SketchyPhone-Client#14
- [x] sopra-fs24-group-25/SketchyPhone-Client#15
- [x] sopra-fs24-group-25/SketchyPhone-Client#18
- [x] sopra-fs24-group-25/SketchyPhone-Client#17

### Server Development Tasks
- [x] sopra-fs24-group-25/SketchyPhone-Server#34
- [x] sopra-fs24-group-25/SketchyPhone-Server#35
- [x] sopra-fs24-group-25/SketchyPhone-Server#36
- [x] sopra-fs24-group-25/SketchyPhone-Server#37
- [x] sopra-fs24-group-25/SketchyPhone-Server#38
- [x] sopra-fs24-group-25/SketchyPhone-Server#39
