### ISSUE TITLE
As a user in an active game session I want to be able to be informed about the time left I have to complete the current action.

### ISSUE THREAD

**Issue by vichcruz** [sopra-fs24-group-25/SketchyPhone-Server#7]
### Acceptance Criteria
- [x] A timer is shown to the user, indicating the remaining time left to complete this action.
- [x] Auditory signals are used to remind a user about the start and remaining time left of the current action.
- [x] It is possible for a user to enable/disable the audio of the current game session.

### Client Development Tasks
- [x] sopra-fs24-group-25/SketchyPhone-Client#1
- [x] sopra-fs24-group-25/SketchyPhone-Client#2
- [x] sopra-fs24-group-25/SketchyPhone-Client#3
- [x] sopra-fs24-group-25/SketchyPhone-Client#4
