### ISSUE TITLE
As a user I want to be able to upvote different image/text prompts shown during the final presentation in order to reward other users for their creativity.

### ISSUE THREAD

**Issue by vichcruz** [sopra-fs24-group-25/SketchyPhone-Server#8]
### Acceptance Criteria
- [x] When all the images/text prompts are shown at the end of the game, users can upvote image/text prompts.
- [x] The number of votes is unlimited, but restricted to one vote per image/text prompt.
- [x] Users can revoke their vote after already having voted on a prompt, but not when the next prompt is shown.

### Client Development Tasks

- [x] sopra-fs24-group-25/SketchyPhone-Client#51
- [x] sopra-fs24-group-25/SketchyPhone-Client#53
- [x] sopra-fs24-group-25/SketchyPhone-Client#52

### Server Development Tasks

- [x] sopra-fs24-group-25/SketchyPhone-Server#125
- [x] sopra-fs24-group-25/SketchyPhone-Server#126
- [x] sopra-fs24-group-25/SketchyPhone-Server#127
- [x] #143
