### ISSUE TITLE
As a user, I want to be able to see the top three most voted prompts in order to see who was the most creative participant.

### ISSUE THREAD

**Issue by vichcruz** [sopra-fs24-group-25/SketchyPhone-Server#9]
### Acceptance Criteria
- [x] While presenting the top three most voted prompts, audio and visual effects are used to increase the immersion.
- [x] Each of the prompts can be downloaded in an appropriate file format.

### Client Development Tasks
- [x] sopra-fs24-group-25/SketchyPhone-Client#54
- [x] sopra-fs24-group-25/SketchyPhone-Client#55
- [x] sopra-fs24-group-25/SketchyPhone-Client#56
- [x] sopra-fs24-group-25/SketchyPhone-Client#57
- [x] sopra-fs24-group-25/SketchyPhone-Client#58

### Server Development Tasks
- [x] sopra-fs24-group-25/SketchyPhone-Server#133
- [x] sopra-fs24-group-25/SketchyPhone-Server#134
- [x] sopra-fs24-group-25/SketchyPhone-Server#135
